"""Hand-verified seed questions so the app works without any AI provider.

Row: (category, topic, difficulty, prompt, [A, B, C, D], correct_letter, explanation)
"""

Q = [
    # ---- Quantitative ----
    ("quantitative", "percentages", "easy", "What is 20% of 250?", ["40", "50", "60", "45"], "B",
     "20% = 1/5, and 250 / 5 = 50."),
    ("quantitative", "profit-loss", "easy", "An item bought for ₹800 is sold for ₹1,000. What is the profit percentage?",
     ["20%", "22.5%", "25%", "30%"], "C", "Profit = 200. Profit % = 200 / 800 × 100 = 25%."),
    ("quantitative", "ratios", "easy", "Two numbers are in the ratio 2 : 3 and their sum is 50. What is the smaller number?",
     ["15", "20", "25", "30"], "B", "Total parts = 5, so one part = 10. The smaller number = 2 × 10 = 20."),
    ("quantitative", "averages", "medium",
     "The average of 5 numbers is 20. When a sixth number is added, the average becomes 22. What is the sixth number?",
     ["30", "32", "34", "36"], "B", "New total = 6 × 22 = 132; old total = 5 × 20 = 100. Sixth number = 132 − 100 = 32."),
    ("quantitative", "time-work", "medium",
     "A can finish a job in 12 days and B in 24 days. Working together, how many days do they need?",
     ["6", "8", "9", "10"], "B", "Combined rate = 1/12 + 1/24 = 3/24 = 1/8 per day, so 8 days."),
    ("quantitative", "time-distance", "medium",
     "A car travels at 60 km/h for 2.5 hours and then at 40 km/h for 1.5 hours. What is its average speed for the whole trip?",
     ["50 km/h", "52.5 km/h", "54 km/h", "55 km/h"], "B",
     "Distance = 150 + 60 = 210 km; time = 4 h. Average speed = 210 / 4 = 52.5 km/h."),
    ("quantitative", "probability", "medium", "Two fair dice are rolled. What is the probability that the sum is 7?",
     ["1/12", "1/9", "1/6", "5/36"], "C", "Six of the 36 outcomes sum to 7: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1). 6/36 = 1/6."),
    ("quantitative", "probability", "medium",
     "A bag has 3 red and 2 blue balls. Two balls are drawn without replacement. What is the probability that both are red?",
     ["3/10", "9/25", "2/5", "1/5"], "A", "(3/5) × (2/4) = 6/20 = 3/10."),
    ("quantitative", "permutations", "medium", "In how many distinct ways can the letters of the word LEVEL be arranged?",
     ["120", "60", "30", "24"], "C", "5 letters with L repeated twice and E repeated twice: 5! / (2! × 2!) = 120 / 4 = 30."),
    ("quantitative", "algebra", "medium", "If x + 1/x = 3, what is the value of x² + 1/x²?",
     ["5", "7", "9", "11"], "B", "Square both sides: x² + 2 + 1/x² = 9, so x² + 1/x² = 7."),
    ("quantitative", "time-work", "medium",
     "A pipe fills a tank in 6 hours and another pipe empties it in 12 hours. If both are open, how long to fill the empty tank?",
     ["8 hours", "10 hours", "12 hours", "18 hours"], "C", "Net rate = 1/6 − 1/12 = 1/12 per hour, so 12 hours."),
    ("quantitative", "number-systems", "hard", "What is the remainder when 2¹⁰ is divided by 7?",
     ["1", "2", "3", "4"], "B", "2³ = 8 ≡ 1 (mod 7). So 2¹⁰ = (2³)³ × 2 ≡ 1 × 2 = 2."),

    # ---- Logical ----
    ("logical", "series", "easy", "Find the next number: 2, 6, 12, 20, 30, ?", ["38", "40", "42", "44"], "C",
     "The terms are n(n+1): 1×2, 2×3, 3×4, 4×5, 5×6. Next is 6×7 = 42."),
    ("logical", "series", "easy", "Find the next number: 3, 6, 12, 24, ?", ["30", "36", "48", "60"], "C", "Each term doubles the previous one."),
    ("logical", "series", "easy", "Find the next letter: A, C, E, G, ?", ["H", "I", "J", "K"], "B", "The pattern skips one letter each time: A, C, E, G, I."),
    ("logical", "coding-decoding", "easy", "If CAT is coded as DBU (each letter shifted by +1), how is DOG coded?",
     ["EPH", "EPG", "DPH", "FPH"], "A", "D→E, O→P, G→H, giving EPH."),
    ("logical", "blood-relations", "medium", "A is B's sister and B is C's father. How is A related to C?",
     ["Mother", "Aunt", "Grandmother", "Cousin"], "B", "A is the sister of C's father, which makes her C's paternal aunt."),
    ("logical", "syllogisms", "medium",
     "Statements: All cats are animals. Some animals are dogs. Conclusion: Some cats are dogs. Does the conclusion follow?",
     ["Follows definitely", "Does not follow", "Follows only if all dogs are animals", "Follows only if all animals are cats"], "B",
     "'Some animals are dogs' does not tell us those dogs overlap with cats. The conclusion is not guaranteed."),
    ("logical", "direction-sense", "medium",
     "A man walks 5 km north, then 12 km east. How far is he from his starting point in a straight line?",
     ["13 km", "15 km", "17 km", "7 km"], "A", "Right triangle with legs 5 and 12: √(25 + 144) = √169 = 13 km."),
    ("logical", "data-interpretation", "easy", "A company's revenue was ₹200 crore in 2022 and ₹250 crore in 2023. What is the percentage growth?",
     ["20%", "22%", "25%", "50%"], "C", "Growth = (250 − 200) / 200 × 100 = 25%."),

    # ---- Verbal ----
    ("verbal", "grammar", "easy", "Choose the correct option: Neither of the boys ___ present.", ["were", "was", "are", "have been"], "B",
     "'Neither' takes a singular verb, so 'was'."),
    ("verbal", "vocabulary", "easy", "Choose the synonym of BENEVOLENT.", ["Cruel", "Kind", "Lazy", "Angry"], "B",
     "Benevolent means well-meaning and kind."),
    ("verbal", "vocabulary", "easy", "Choose the antonym of SCARCE.", ["Rare", "Limited", "Abundant", "Precious"], "C",
     "Scarce means in short supply; the opposite is abundant."),
    ("verbal", "sentence-correction", "easy", "Which sentence is grammatically correct?",
     ["She don't like coffee.", "She doesn't likes coffee.", "She doesn't like coffee.", "She not like coffee."], "C",
     "With a third-person singular subject, use 'doesn't' plus the base verb 'like'."),
    ("verbal", "idioms", "easy", "What does the idiom 'once in a blue moon' mean?",
     ["Very frequently", "Very rarely", "At night", "Without warning"], "B", "It refers to something that happens very rarely."),

    # ---- DSA ----
    ("dsa", "complexity", "easy", "What is the time complexity of binary search on a sorted array of n elements?",
     ["O(n)", "O(log n)", "O(n log n)", "O(1)"], "B", "Each step halves the search space, giving O(log n)."),
    ("dsa", "stacks-queues", "easy", "Which data structure follows the Last-In-First-Out (LIFO) principle?",
     ["Queue", "Stack", "Heap", "Graph"], "B", "A stack removes the most recently added element first."),
    ("dsa", "hashing", "easy", "What is the average-case time complexity of lookup in a well-designed hash table?",
     ["O(1)", "O(log n)", "O(n)", "O(n²)"], "A", "With a good hash function and load factor, lookups are O(1) on average."),
    ("dsa", "graphs", "easy", "Which data structure is typically used to implement Breadth-First Search (BFS)?",
     ["Stack", "Queue", "Priority queue", "Binary tree"], "B", "BFS visits nodes level by level, which a FIFO queue supports."),
    ("dsa", "sorting", "medium", "What is the worst-case time complexity of Quick Sort?",
     ["O(n log n)", "O(n)", "O(n²)", "O(log n)"], "C", "If pivots are consistently the smallest or largest element, partitions are unbalanced and the cost is O(n²)."),
    ("dsa", "trees", "medium", "The in-order traversal of a binary search tree visits the keys in what order?",
     ["Random order", "Descending order", "Ascending (sorted) order", "Level order"], "C",
     "In-order visits left subtree, node, then right subtree, which yields sorted keys in a BST."),
    ("dsa", "graphs", "medium", "What is the minimum number of edges required to keep a connected undirected graph with n vertices connected?",
     ["n", "n − 1", "n + 1", "n / 2"], "B", "A spanning tree connects n vertices using exactly n − 1 edges."),
    ("dsa", "sorting", "medium", "Which of these sorting algorithms is stable in its standard implementation?",
     ["Quick Sort", "Heap Sort", "Merge Sort", "Selection Sort"], "C", "Merge sort preserves the relative order of equal elements."),
    ("dsa", "linked-lists", "medium", "Which technique detects a cycle in a linked list using O(1) extra space?",
     ["Hashing every node", "Floyd's slow and fast pointers", "Recursion", "Sorting the list"], "B",
     "Two pointers moving at different speeds meet inside a cycle if one exists."),
    ("dsa", "dynamic-programming", "medium", "What is the length of the Longest Common Subsequence of 'ABC' and 'AC'?",
     ["1", "2", "3", "0"], "B", "'AC' appears in both strings in order, so the LCS length is 2."),
    ("dsa", "dynamic-programming", "hard",
     "In how many distinct ways can you climb 5 stairs if you may take 1 or 2 steps at a time?",
     ["5", "8", "10", "13"], "B", "Ways follow Fibonacci: f(1)=1, f(2)=2, f(3)=3, f(4)=5, f(5)=8."),

    # ---- OOP ----
    ("oop", "polymorphism", "easy", "Which best describes polymorphism?",
     ["Hiding data inside a class", "One interface with many forms of behavior", "Creating objects from classes", "Deriving a class from another"], "B",
     "Polymorphism lets the same interface produce different behavior depending on the actual object."),
    ("oop", "encapsulation", "easy", "Encapsulation refers to:",
     ["Bundling data with the methods that operate on it and restricting direct access", "Inheriting from multiple classes", "Overloading operators", "Compiling code to bytecode"], "A",
     "Encapsulation groups state and behavior together and controls access to internals."),
    ("oop", "abstraction", "medium", "Which statement about an abstract class is true in most OOP languages?",
     ["It can be instantiated directly", "It cannot be instantiated directly", "It cannot have any methods", "It must have only private members"], "B",
     "Abstract classes are meant to be extended; they cannot be instantiated on their own."),
    ("oop", "inheritance", "medium", "Method overriding happens when:",
     ["Two methods in one class share a name but differ in parameters", "A subclass provides its own implementation of a parent's method with the same signature", "A method is declared private", "A class has multiple constructors"], "B",
     "Overriding replaces the parent implementation in a subclass, using the same signature."),
    ("oop", "inheritance", "medium", "The 'diamond problem' is associated with:",
     ["Single inheritance", "Multiple inheritance", "Method overloading", "Static binding"], "B",
     "When a class inherits from two classes that share a common ancestor, ambiguity arises about which inherited member to use."),

    # ---- DBMS ----
    ("dbms", "keys", "easy", "Which property must a primary key satisfy?",
     ["It must be unique and non-null", "It may contain duplicates", "It can be null", "It must be a string"], "A",
     "A primary key uniquely identifies each row and cannot be NULL."),
    ("dbms", "transactions", "easy", "In the ACID properties, what does 'I' stand for?",
     ["Integrity", "Isolation", "Inheritance", "Indexing"], "B", "Isolation means concurrent transactions do not interfere with each other."),
    ("dbms", "joins", "easy", "An INNER JOIN between two tables returns:",
     ["All rows from both tables", "Only rows with matching values in both tables", "All rows from the left table", "Only rows with no match"], "B",
     "INNER JOIN keeps only rows where the join condition matches in both tables."),
    ("dbms", "normalization", "medium", "Third Normal Form (3NF) primarily removes which kind of dependency?",
     ["Partial dependency", "Transitive dependency", "Multivalued dependency", "Join dependency"], "B",
     "3NF requires that non-key attributes depend only on the key, not on other non-key attributes."),
    ("dbms", "indexing", "medium", "What is the main trade-off of adding an index to a table?",
     ["Faster writes, slower reads", "Faster reads, slower writes and extra storage", "No effect on performance", "Faster reads and faster writes"], "B",
     "Indexes speed up lookups but must be maintained on every insert, update or delete."),

    # ---- OS ----
    ("os", "processes-threads", "easy", "What do threads of the same process share?",
     ["Stack and registers", "Address space and open files", "Nothing", "Program counter"], "B",
     "Threads share the process's memory and resources, but each has its own stack, registers and program counter."),
    ("os", "synchronization", "easy", "A semaphore is primarily used for:",
     ["Data compression", "Process synchronization", "Memory allocation", "Disk scheduling"], "B",
     "Semaphores coordinate access to shared resources between processes or threads."),
    ("os", "deadlocks", "medium", "Which of these is NOT one of the four necessary conditions for deadlock?",
     ["Mutual exclusion", "Hold and wait", "Preemption", "Circular wait"], "C",
     "The condition is 'no preemption'. If resources could be preempted, deadlock could be broken."),
    ("os", "cpu-scheduling", "medium",
     "Processes P1, P2, P3 arrive at time 0 with CPU bursts 5, 3 and 2 ms and run in that order under FCFS. What is the average waiting time?",
     ["3.33 ms", "4.33 ms", "5 ms", "6 ms"], "B", "Waiting times are 0, 5 and 8. Average = 13 / 3 ≈ 4.33 ms."),
    ("os", "memory-management", "medium", "Belady's anomaly, where more frames can cause more page faults, occurs with which page replacement policy?",
     ["LRU", "Optimal", "FIFO", "Clock with reference bits only"], "C", "FIFO can show more page faults when the number of frames increases."),
    ("os", "cpu-scheduling", "hard",
     "Processes with CPU bursts 5, 3 and 2 ms all arrive at time 0. What is the average waiting time under Shortest Job First (non-preemptive)?",
     ["2 ms", "2.33 ms", "3 ms", "4.33 ms"], "B", "Run order 2, 3, 5 gives waits 0, 2 and 5. Average = 7 / 3 ≈ 2.33 ms."),

    # ---- Networks ----
    ("networks", "protocols", "easy", "Which port does HTTPS use by default?", ["80", "21", "443", "8080"], "C", "HTTPS defaults to port 443; HTTP uses 80."),
    ("networks", "transport", "easy", "Which of these transport protocols is connectionless?", ["TCP", "UDP", "SCTP with associations", "FTP"], "B",
     "UDP sends datagrams without establishing a connection first."),
    ("networks", "osi-model", "easy", "Routing of packets between networks happens at which OSI layer?",
     ["Data Link", "Network", "Transport", "Session"], "B", "The Network layer (IP) handles logical addressing and routing."),
    ("networks", "dns", "easy", "What does DNS do?", ["Encrypts traffic", "Translates domain names to IP addresses", "Assigns MAC addresses", "Compresses web pages"], "B",
     "The Domain Name System maps human-readable names to IP addresses."),
    ("networks", "addressing", "medium", "The address 192.168.1.10 belongs to which classful IPv4 address class?",
     ["Class A", "Class B", "Class C", "Class D"], "C", "Class C covers 192.0.0.0 to 223.255.255.255."),
    ("networks", "transport", "medium", "What is the correct sequence of the TCP three-way handshake?",
     ["SYN, ACK, SYN-ACK", "SYN, SYN-ACK, ACK", "ACK, SYN, SYN-ACK", "SYN-ACK, SYN, ACK"], "B",
     "The client sends SYN, the server replies SYN-ACK, and the client confirms with ACK."),

    # ---- Software Engineering ----
    ("software-eng", "agile", "easy", "In Scrum, a sprint is:", ["A daily meeting", "A time-boxed iteration of work", "A bug report", "A deployment tool"], "B",
     "A sprint is a fixed-length iteration, typically 1 to 4 weeks."),
    ("software-eng", "testing", "easy", "Unit testing focuses on:",
     ["The whole system end to end", "Individual components in isolation", "User acceptance", "Network latency"], "B",
     "Unit tests verify the smallest testable parts of the code in isolation."),
    ("software-eng", "version-control", "easy", "Which Git command creates a new branch and switches to it?",
     ["git branch -d feature", "git checkout -b feature", "git merge feature", "git stash feature"], "B",
     "`git checkout -b feature` (or `git switch -c feature`) creates and switches."),
    ("software-eng", "design-principles", "easy", "In the SOLID principles, what does 'S' stand for?",
     ["Single Responsibility", "Static Binding", "Simple Syntax", "Stateless Service"], "A",
     "A class should have one reason to change."),
    ("software-eng", "sdlc", "easy", "Which SDLC model follows strictly sequential phases?", ["Agile", "Waterfall", "Spiral", "Prototype"], "B",
     "Waterfall moves through requirements, design, implementation, testing and maintenance in order."),
]
